language: clojure
lein: lein2
script: lein midje && lein uberjar
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "hackersome.public"
